server:
  port: 8877
spring:
  datasource:
    url: jdbc:mysql://10.139.60.82:3306/vmc_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: dev
    password: dev123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 275526034@qq.com
    password: eaghumghtjuebjge
    default-encoding: UTF-8
mybatis-plus:
  type-aliases-package: com.wjp.dao.entity
  mapper-locations: "classpath:mapper/**/*Mapper.xml"
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    cache-enabled: false
  global-config:
    banner: false
    db-config:
      id-type: auto
      workerId: ${workerId}
      datacenterId: ${datacenterId}
      capital-mode: true
      field-strategy: not_empty
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql

